<?php

/**
 * @file
 * Contains ldap_feeds.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ldap_feeds_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ldap_feeds module.
    case 'help.page.ldap_feeds':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The LDAP Feeds.') . '</p>';
      return $output;

    default:
  }
}
