<?php

/**
 * @file
 * Contains ldap_rest.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ldap_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ldap_rest module.
    case 'help.page.ldap_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The LDAP REST.') . '</p>';
      return $output;

    default:
  }
}
